import React, { useEffect, useRef, useState } from 'react';
import { IconFileText, IconStack2, IconMessageCircle, IconUsers, IconChevronDown, IconPencil, IconX, IconMenu2 } from '@tabler/icons-react';
import '@fontsource-variable/source-sans-3';

const initial = {title:'Reschedule an appointment', statement:'The system shall allow a customer to reschedule a confirmed appointment to an available time at least 24 hours before its start.', condition:'The appointment must have confirmed status.'};
const storageKey = 'pew-specification-editing-study-v1';
function restore() { try { const s=JSON.parse(sessionStorage.getItem(storageKey)); return s && typeof s.saved?.statement==='string' && typeof s.saved?.title==='string' && typeof s.saved?.condition==='string' ? s : {saved:initial,draft:null,revision:1}; } catch { return {saved:initial,draft:null,revision:1}; } }
const Icon = ({as:Component,...props}) => <Component size={22} stroke={1.6} aria-hidden="true" {...props}/>;
function Button({children,primary=false,className='',...props}) {return <button type="button" className={`c-button ${primary?'c-button--primary':''} ${className}`} {...props}>{children}</button>}
function RequirementHeading({reference,children}) {return <h3 className="flex min-w-0 items-baseline gap-3 text-2xl font-semibold leading-snug"><span className="shrink-0 text-base font-normal text-muted">{reference}</span><span className="min-w-0 text-balance">{children}</span></h3>}
export function App(){
 const [currentSection,setCurrentSection]=useState('specification');
 const [wide,setWide]=useState(()=>window.matchMedia('(min-width:80rem)').matches);
 useEffect(()=>{const m=window.matchMedia('(min-width:80rem)');const update=()=>setWide(m.matches);m.addEventListener('change',update);return ()=>m.removeEventListener('change',update)},[]);
 const [data,setData]=useState(restore), [selected,setSelected]=useState(false), [editing,setEditing]=useState(false), [panel,setPanel]=useState(null), [outline,setOutline]=useState(false), [expanded,setExpanded]=useState(true), [theme,setTheme]=useState('ochre'), [notice,setNotice]=useState(''), [storageError,setStorageError]=useState(false), [discard,setDiscard]=useState(false), [dismissed,setDismissed]=useState(false);
 const statement=useRef(null), editButton=useRef(null), reviewButton=useRef(null), panelHeading=useRef(null), article=useRef(null);
 useEffect(()=>{try {sessionStorage.setItem(storageKey,JSON.stringify(data));setStorageError(false)}catch {setStorageError(true)}},[data]);
 useEffect(()=>{if(editing)statement.current?.focus({preventScroll:true})},[editing]);
 useEffect(()=>{if(panel)panelHeading.current?.focus({preventScroll:wide})},[panel]);
 const begin=()=>{setData(d=>({...d,draft:d.draft??{...d.saved}}));setSelected(true);setEditing(true);setDiscard(false);setNotice('');requestAnimationFrame(()=>article.current?.scrollIntoView({block:'nearest'}))};
 const finish=()=>{const d=data.draft;if(!d?.title.trim()||!d.statement.trim())return;const changed=JSON.stringify(d)!==JSON.stringify(data.saved);setData({...data,saved:{...d,title:d.title.trim(),statement:d.statement.trim()},draft:null,revision:data.revision+(changed?1:0)});setEditing(false);setSelected(true);setNotice(changed?'Changes saved to the specification.':'No changes to save.');setDiscard(false);requestAnimationFrame(()=>editButton.current?.focus({preventScroll:true}))};
 const change=(key,value)=>setData(d=>({...d,draft:{...d.draft,[key]:value}}));
 const leave=()=>{setEditing(false);setSelected(false);setDiscard(false);if(data.draft)setNotice('Draft kept. The saved specification is unchanged.')};
 const openPanel=(value)=>{setPanel(value);setSelected(true)};
 const closePanel=()=>{setPanel(null);requestAnimationFrame(()=>reviewButton.current?.focus({preventScroll:true}))};
 const discardDraft=()=>{setData(d=>({...d,draft:null}));setEditing(false);setDiscard(false);setNotice('Changes discarded. Saved requirement restored.');requestAnimationFrame(()=>editButton.current?.focus({preventScroll:true}))};
 const jump=(id)=>{setCurrentSection(id==='requirement'?'specification':id);leave();setOutline(false);requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({block:'start'}))};
 const panelContent=panel && <aside className="c-context" aria-label="Requirement context"><div className="flex items-center justify-between gap-3"><h2 ref={panelHeading} tabIndex={-1} className="text-xl font-semibold">{panel==='review'?'Review feedback':panel==='policy'?'Supporting source':panel==='feature'?'Core Feature':'Acceptance criterion'}</h2><Button aria-label="Close context" onClick={closePanel}><Icon as={IconX}/></Button></div><p className="mbs-5 text-muted">FR-012 · {data.saved.title}</p>{panel==='review'?<><h3 className="mbs-8 font-semibold">Requirements quality</h3><p className="mbs-5"><span className="rounded bg-selection px-2 py-1 text-sm">{dismissed?'Dismissed finding':'Finding · Ambiguity'}</span></p><h3 className="mbs-4 text-2xl font-semibold leading-snug">Which timezone determines the 24-hour cutoff?</h3><p className="mbs-4 leading-relaxed">The requirement does not specify whether the cutoff uses the customer’s timezone or the appointment location’s timezone.</p><h3 className="mbs-8 font-semibold">Related evidence</h3><button className="c-link mbs-4" onClick={()=>setPanel('policy')}>Customer booking policy</button><button className="c-link mbs-2" onClick={()=>setPanel('AC-022')}>AC-022</button><p className="mbs-6 border-t border-line pbs-5 text-muted">This finding has not changed the specification.</p><Button primary className="mbs-6 w-full" onClick={begin}>{data.draft?'Keep editing draft':'Edit requirement'}</Button><Button className="mbs-2 w-full" onClick={()=>setDismissed(!dismissed)}>{dismissed?'Restore finding':'Dismiss finding'}</Button></>:panel==='policy'?<><h3 className="mbs-8 text-2xl font-semibold">Customer booking policy</h3><p className="mbs-4 leading-relaxed">Customers may change a confirmed appointment until 24 hours before it starts. The new time must be available.</p><p className="mbs-4 text-muted">Source note · The policy does not specify a timezone.</p><Button className="mbs-6" onClick={()=>setPanel('review')}>Back to review feedback</Button></>:panel==='feature'?<><h3 className="mbs-8 text-2xl font-semibold">Appointment changes</h3><p className="mbs-4 leading-relaxed">Allow customers to change an existing booking while respecting availability and the rescheduling policy.</p></>:<><h3 className="mbs-8 text-2xl font-semibold">{panel}</h3><p className="mbs-4 leading-relaxed">{panel==='AC-021'?'An eligible rescheduling replaces the original time with the selected available time.':'An appointment within the 24-hour cutoff cannot be rescheduled.'}</p><p className="mbs-5 text-muted">Validates FR-012 · Reschedule an appointment</p><Button className="mbs-6" onClick={()=>setPanel('review')}>Back to review feedback</Button></>}</aside>;
 return <div data-theme={theme} className="min-h-dvh bg-canvas text-ink">
 <a href="#specification" className="sr-only focus:not-sr-only">Skip to specification</a>
 <header className="c-topbar"><div className="c-topbar__identity flex min-w-0 items-center gap-5"><Button className="lg:hidden" aria-label="Toggle specification outline" aria-controls="specification-outline" aria-expanded={outline} onClick={()=>setOutline(!outline)}><Icon as={IconMenu2}/></Button><span className="font-semibold text-accent">Workbench</span></div><div className="hidden lg:block flex-1 text-muted text-lg">Appointment booking <span className="mx-3">/</span> Specification</div><div className="flex items-center gap-3 text-sm"><span className="hidden sm:inline text-muted">Interaction study</span><label className="flex items-center gap-2">Palette<select aria-label="Palette" value={theme} onChange={e=>setTheme(e.target.value)} className="rounded border border-line bg-canvas p-2"><option value="ochre">Ochre</option><option value="blue">Blue</option></select></label></div></header>
 <div className="flex items-start">
 <nav id="specification-outline" aria-label="Specification outline" className={`c-sidebar ${outline?'c-sidebar--open':''}`}>
 <div className="space-y-1 border-b border-line pbe-6"><div className="flex items-center gap-4 rounded bg-selection px-4 py-3 font-semibold text-accent"><Icon as={IconFileText}/>Specification</div>{[[IconStack2,'Sources','policy'],[IconMessageCircle,'Conversations','review'],[IconUsers,'Collaboration requests','review']].map(([i,label,target])=><div key={label} className="flex min-h-11 w-full items-center gap-4 rounded px-4 py-3 text-left"><Icon as={i}/>{label}</div>)}</div>
 <div className="mbs-6 space-y-1">{[['Product overview','overview'],['Goals and success criteria','goals'],['Core features','features']].map(([name,id])=><button className="c-outline-link" aria-current={currentSection===id?'location':undefined} key={id} onClick={()=>jump(id)}>{name}</button>)}<div className="flex items-center"><button className="c-outline-link font-semibold text-accent" aria-current={currentSection==='specification'?'location':undefined} onClick={()=>jump('specification')}>Functional requirements</button><Button aria-label="Expand rescheduling outline" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><Icon as={IconChevronDown}/></Button></div>{expanded&&<button className="c-outline-link ps-12 text-accent" onClick={()=>jump('requirement')}>Rescheduling</button>}<button className="c-outline-link" aria-current={currentSection==='criteria'?'location':undefined} onClick={()=>jump('criteria')}>Acceptance criteria</button><button className="c-outline-link" aria-current={currentSection==='questions'?'location':undefined} onClick={()=>jump('questions')}>Risks and open questions</button></div>
 </nav>
 <main id="specification" tabIndex={-1} className="min-w-0 flex-1" onClick={e=>{if(!e.target.closest('article,button,a,input,textarea,select,aside'))leave()}}>
 <div className="border-b border-line px-6 py-4 text-muted lg:hidden">Appointment booking <span className="mx-3">/</span> Specification</div>
 <div className={`l-workspace ${panel?'l-workspace--context':''}`}>
 <div className="min-w-0 px-6 pbs-9 pbe-20 lg:px-16 lg:pbs-12">
 <h1 className="text-4xl font-semibold tracking-tight lg:text-5xl">Functional requirements</h1><h2 className="mbs-10 text-3xl font-semibold">Rescheduling</h2>
 <article id="requirement" ref={article} className="c-requirement mbs-7" data-state={editing?'editing':selected?'selected':'reading'} onClick={e=>{if(!e.target.closest('button,a,input,textarea')&&!window.getSelection()?.toString())setSelected(true)}}>
 {editing?<div className="flex items-center justify-between gap-3"><span className="text-muted">FR-012</span>{data.draft&&<span className="text-sm text-muted">Private draft</span>}</div>:<div className="flex items-start justify-between gap-3"><RequirementHeading reference="FR-012">{data.saved.title}</RequirementHeading><div className="flex shrink-0 flex-wrap items-center justify-end gap-2">{data.draft&&<span className="text-sm text-muted">Private draft</span>}<Button ref={editButton} className="c-requirement__edit" aria-label={data.draft?'Keep editing draft':'Edit requirement'} onClick={begin}><span className="flex items-center gap-2"><Icon as={IconPencil}/><span>{data.draft?'Keep editing draft':'Edit'}</span></span></Button></div></div>}
 {editing?<form onSubmit={e=>{e.preventDefault();finish()}} className="mbs-1" aria-label="Edit FR-012"><label className="block text-sm text-muted" htmlFor="requirement-title">Title</label><input id="requirement-title" className="c-field c-field--title" value={data.draft.title} onChange={e=>change('title',e.target.value)} required/><label className="mbs-5 block text-sm text-muted" htmlFor="requirement-statement">Requirement statement</label><textarea ref={statement} id="requirement-statement" className="c-field" rows={4} value={data.draft.statement} onChange={e=>change('statement',e.target.value)} required/><label className="mbs-5 block font-semibold" htmlFor="requirement-condition">Conditions and constraints</label><textarea id="requirement-condition" className="c-field mbs-2" rows={2} value={data.draft.condition} onChange={e=>change('condition',e.target.value)}/><div className="mbs-5 flex flex-wrap items-center gap-2"><button className="c-button c-button--primary" type="submit">Done editing</button><Button onClick={()=>setDiscard(true)}>Discard changes</Button><Button onClick={leave}>Return to reading</Button></div><p className="mbs-3 text-sm text-muted">Only Done editing updates the specification. You can leave and continue this draft later.</p></form>:<><p className="mbs-5 whitespace-pre-wrap text-xl leading-relaxed" data-testid="saved-statement">{data.saved.statement}</p><h4 className="mbs-7 text-xl font-semibold">Conditions and constraints</h4>{data.saved.condition?<ul className="mbs-3 list-disc ps-6 text-xl leading-relaxed"><li className="whitespace-pre-wrap">{data.saved.condition}</li></ul>:<p className="mbs-3 text-muted">No additional conditions.</p>}{data.draft&&selected&&<div className="mbs-4 flex flex-wrap gap-2"><Button onClick={()=>setDiscard(true)}>Discard changes</Button><Button primary onClick={finish}>Done editing</Button></div>}</>}
 {discard&&<div className="mbs-4 rounded border border-line bg-sidebar p-4"><p>Discard the private changes to FR-012?</p><div className="mbs-3 flex gap-2"><Button onClick={discardDraft}>Discard draft</Button><Button primary onClick={()=>setDiscard(false)}>Keep draft</Button></div></div>}
 <div role="status" className="text-sm text-muted">{notice&&<p className="mbs-4">{notice}</p>}{storageError&&<p className="mbs-3">Browser storage is unavailable. Keep this tab open to retain your study changes.</p>}</div>
 </article>
 <section id="criteria" className="mbs-8"><h3 className="text-xl font-semibold">Acceptance criteria</h3><div className="mbs-4 space-y-3">{[['AC-021','An eligible rescheduling replaces the original time with the selected available time.'],['AC-022','An appointment within the 24-hour cutoff cannot be rescheduled.']].map(([id,text])=><div key={id} className="flex items-baseline gap-4 text-xl leading-relaxed"><button className="c-link shrink-0" onClick={()=>openPanel(id)}>{id}</button><p>{text}</p></div>)}</div></section>
 <section className="mbs-7"><h3 className="text-xl font-semibold">Supporting information</h3><div className="mbs-3 flex flex-col items-start gap-1 text-xl"><button className="c-link" onClick={()=>openPanel('feature')}>Feature: Appointment changes</button><button className="c-link" onClick={()=>openPanel('policy')}>Customer booking policy</button><button ref={reviewButton} className="c-link" aria-expanded={panel==='review'} onClick={()=>panel==='review'?closePanel():openPanel('review')}>Review feedback · {dismissed?'1 dismissed finding':'1 finding'}</button></div></section>
 {panel&&!wide&&<div className="c-mobile-context mbs-6">{panelContent}</div>}
 <section className="mbs-6 border-t border-line pbs-6" id="next-requirement"><RequirementHeading reference="FR-013">Confirm the new appointment time</RequirementHeading><p className="mbs-4 text-xl leading-relaxed">The system shall display the updated appointment time after a successful rescheduling.</p></section>
 <section className="mbs-16 border-t border-line pbs-8" id="overview"><h2 className="text-3xl font-semibold">Product overview</h2><p className="mbs-4 text-xl leading-relaxed">Appointment booking helps customers find a suitable time, confirm their booking and manage changes with confidence.</p></section>
 <section className="mbs-12" id="goals"><h2 className="text-3xl font-semibold">Goals and success criteria</h2><p className="mbs-4 text-xl leading-relaxed">Help customers manage appointments independently, with clear confirmation of every change.</p></section>
 <section className="mbs-12" id="features"><h2 className="text-3xl font-semibold">Core features</h2><h3 className="mbs-4 text-xl font-semibold">Appointment changes</h3><p className="mbs-3 text-xl leading-relaxed">Reschedule a confirmed booking within the permitted window.</p></section>
 <section className="mbs-12" id="questions"><h2 className="text-3xl font-semibold">Risks and open questions</h2><p className="mbs-4 text-xl leading-relaxed">Which timezone should determine the rescheduling cutoff?</p><Button className="mbs-4" onClick={()=>jump('requirement')}>Return to FR-012</Button></section>
 <p className="mbs-16 text-sm text-muted">Illustrative specification · Revision {data.revision} · Changes stay in this browser tab.</p>
 </div><div className="c-desktop-context">{wide&&panelContent}</div>
 </div></main></div></div>
}
